---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: {{ .Release.Name | default .Values.rtsDefaultName }}-default-tls
spec:
  commonName: {{ .Release.Name | default .Values.rtsDefaultName }}
  dnsNames:
  - {{ .Release.Name | default .Values.rtsDefaultName }}.services.cluster.svc.local
  - {{ .Release.Name | default .Values.rtsDefaultName }}.services.cluster.svc
  - {{ .Release.Name | default .Values.rtsDefaultName }}.services
  duration: 720h0m0s
  issuerRef:
    kind: Issuer
    name: cert-manager-issuer-common
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  keySize: 2048
  renewBefore: 24h0m0s
  secretName: {{ .Release.Name | default .Values.rtsDefaultName }}-default-tls