---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "{{ .Release.Name | default .Values.rtsDefaultName }}-sma-kafkarule"
  labels:
    app.kubernetes.io/name: {{ .Release.Name | default .Values.rtsDefaultName }}
spec:
  host: "cluster-kafka-bootstrap.sma.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "{{ .Release.Name | default .Values.rtsDefaultName }}-sma-collectorrule"
  labels:
    app.kubernetes.io/name: {{ .Release.Name | default .Values.rtsDefaultName }}
spec:
  host: "hms-hmcollector.sma.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "{{ .Release.Name | default .Values.rtsDefaultName }}-service"
  labels:
    app.kubernetes.io/name: {{ .Release.Name | default .Values.rtsDefaultName }}
spec:
  host: "{{ .Release.Name | default .Values.rtsDefaultName }}"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL