---
apiVersion: batch/v1
kind: Job
metadata:
  name: cray-hms-rts-init-deleter
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: “false”
    spec:
      restartPolicy: OnFailure
      serviceAccountName: "cray-hms-rts"
      containers:
        - name: job-deleter
          image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
          imagePullPolicy: "{{ .Values.kubectl.image.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - set -x;
            echo "Deleting Jobs";
            kubectl -n services delete job cray-hms-rts-init;
            exit 0
---
apiVersion: batch/v1
kind:       Job
metadata:
  name: cray-hms-rts-init
  labels:
    app: cray-hms-rts-init
spec:
  template:
    metadata:
      labels:
        app: cray-hms-rts-init
    spec:
      serviceAccountName: "cray-rts-vault-watcher"
      restartPolicy: OnFailure
      containers:
        - name: cray-hms-rts-init
          env:
            - name:  VAULT_ADDR
              value: "http://cray-vault.vault:8200"
            - name:  VAULT_SKIP_VERIFY
              value: "true"
            - name:  VAULT_RTS_MAX_CONNECTION_ATTEMPTS
              value: "120"
            - name: VAULT_RTS_DEFAULT_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: cray-hms-rts-credentials
                  key: vault_rts_defaults
            - name: VAULT_PDU_DEFAULT_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: cray-hms-rts-credentials
                  key: vault_pdu_defaults
            - name: JAWS_VAULT_KEYPATH
              valueFrom:
                configMapKeyRef:
                  name: cray-rts-config
                  key: cray-hms-rts.jaws_vault_keypath
          image: {{ .Values.image.repository }}:{{ default .Values.global.appVersion .Values.image.tag }}
          command: ["vault_loader"]
