apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | default .Values.rtsDefaultName }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name | default .Values.rtsDefaultName }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: http
    - port: 443
      name: https
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: {{ .Release.Name | default .Values.rtsDefaultName }}
