{{- if .Values.rtsDoInit }}
{{- if index .Values "cray-service" "sealedSecrets" -}}
{{- range $val := index .Values "cray-service" "sealedSecrets" }}
{{- if $val.kind }}
{{- if eq $val.kind "SealedSecret" }}
---
{{ toYaml $val }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end }}
